version: "3.9"
services:
  datalore:
    image: jetbrains/datalore-server:2023.1
    restart: always
    # ports:
    #   - "8089:8080"
    expose: [ "8081", "5050", "4060" ]
    networks:
      - traefik-public
    volumes:
      - "/home/azat/datalore/datalore-storage:/opt/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DB_PASSWORD: "Azat.AI2021@#."
      DATABASES_DOCKER_NETWORK: "traefik-public"
      SQL_SESSION_DOCKER_NETWORK: "traefik-public"
      DATALORE_PUBLIC_URL: "https://datalore.azat.ai"
    labels:
        - traefik.enable=true
        - traefik.http.services.datalore.loadbalancer.server.port=8080
        - traefik.http.routers.datalore-http.entrypoints=http
        - traefik.http.routers.datalore-http.rule=Host(`datalore.azat.ai`)
        - traefik.http.routers.datalore-https.entrypoints=https
        - traefik.http.routers.datalore-https.rule=Host(`datalore.azat.ai`)
        - traefik.http.routers.datalore-https.tls=true
        - traefik.http.routers.datalore-https.tls.certresolver=le
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.datalore-http.middlewares=https-redirect
    # Traefik End
  postgresql:
    image: jetbrains/datalore-postgres:2023.1
    expose: [ "5432" ]
    networks:
      - traefik-public
    volumes:
      - "/home/azat/datalore/postgresql-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "Azat.AI2021@#."
volumes:
  postgresql-data: { }
  datalore-storage: { }
networks:
  traefik-public:
    external: true

